Make 'mention_count' on ReadState default to 0
The `mention_count` on ReadState is not sent if there are no mentions. This was
causing this error on connection:

```
thread '<main>' panicked at 'connect failed: Decode("Unexpected absent key", "mention_count")', ../src/libcore/result.rs:785
```